name: anonymous_messenger
description: An anonymous messaging app similar to Sarahah
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.25
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  timeago: ^3.6.0
  cached_network_image: ^3.3.0
  flutter_secure_storage: ^9.0.0
  go_router: ^12.1.1
  flutter_animate: ^4.2.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/